project:
  type: website
  output-dir: docs

website:
  title: "**OteaBooks** <small style='font-size: 0.8em;'>*Libros de acceso gratuito*</small>"
  site-url: "https://oteabooks.com"
  navbar:
    collapse: true

format:
  html:
    theme: default      # Un estilo muy limpio y tipografía ligera
    css: custom.scss         # Personalización del color
    toc: false          # Desactivamos el índice lateral para mantener la web limpia
    page-layout: article # Mantiene el contenido perfectamente centrado y legible

editor: visual

